application: hd-website
version: 5
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/root/favicon.ico
  upload: static/root/favicon.ico
- url: /robots.txt
  static_files: static/root/robots.txt
  upload: static/root/robots.txt  
- url: /static
  static_dir: static
  expiration: "1d"
- url: .*
  script: main.app
